### ISSUE TITLE
Introduce a boolean parameter in the watch-release notification for compatibility with M2Release plugin

### ISSUE THREAD

**Issue by gastaldi** [tobias/proddbot#9]
A job in Jenkins may use the [M2 Release plugin](https://wiki.jenkins-ci.org/display/JENKINS/M2+Release+Plugin) in the same job used for a regular Maven project

However, the job notification screen in Jenkins does not allow you to fire notifications to proddbot only when a release happens (see screenshot below)

![screenshot from 2016-12-06 01-20-17](https://cloud.githubusercontent.com/assets/54133/20911834/473df94a-bb52-11e6-8a2c-ed3fa5d86021.png)

Fortunately, an environment variable is set (`IS_M2RELEASEBUILD`) and it would be nice if we could pass this variable to the given URL so proddbot could know when a given notification should trigger the `watch-release-add` IRC command to notify users.

As this parameter may not be provided, and the notification URL is used by other projects (WildFly Swarm for example) the expected behavior would be to not trigger the `watch-release-add` command when the parameter is explicitly false.

Parameter (name TBD) | Triggers `watch-release-add`?
-------------------------- | ----------------------------------------
`release_build=true` |  Yes
`release_build=false` |  No
(not provided)             |  Yes

**Comment by tobias** [comment]
I named the parameter `create_watch`, and it should work as you described above. Let me know if it doesn't :)
